### ISSUE TITLE
pose_to_segments command ModuleNotFoundError 

### ISSUE THREAD

**Issue by J22Melody** [sign-language-processing/transcription#26]
When running the `pose_to_segments` command, getting the following error:

```
Traceback (most recent call last):
  File "/home/zifjia/data/conda/envs/trans/bin/pose_to_segments", line 5, in <module>
    from pose_to_segments.bin import main
  File "/home/zifjia/data/conda/envs/trans/lib/python3.9/site-packages/pose_to_segments/bin.py", line 11, in <module>
    from pose_to_segments.src.utils.probs_to_segments import probs_to_segments
ModuleNotFoundError: No module named 'pose_to_segments.src'
```

Instead, running `python -m pose_to_segments.bin` is fine.

**Comment by AmitMY** [comment]
Moved to https://github.com/sign-language-processing/segmentation
