### ISSUE TITLE
ModuleNotFoundError: No module named 'pose_to_video.stylegan3'

### ISSUE THREAD

**Issue by hacker009-sudo** [sign-language-processing/transcription#29]
@AmitMY , please help me to resolve this issue

**Comment by AmitMY** [comment]
Please fill in a proper issue - specifically:
1. What commands are you running?
2. What is the output?

In general, the `stylegan3` code is still work-in-progress, but if I understand what you are trying to do I might be able to help.

**Comment by hacker009-sudo** [comment]
@AmitMY , I am following the documentation to run the code for pose_to_video and running the below command on colab:

!python /content/transcription/pose_to_video/bin.py --model=stylegan3 --pose=sign.pose --video=sign.mp4

Issue: 

Loading input pose ...
Generating video ...
Traceback (most recent call last):
  File "/content/transcription/pose_to_video/bin.py", line 58, in <module>
    main()
  File "/content/transcription/pose_to_video/bin.py", line 33, in main
    module = importlib.import_module(f"pose_to_video.{args.model}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pose_to_video.stylegan3'


I have even tried with pix_to_pix but same issue: 

ModuleNotFoundError: No module named 'pose_to_video.pix_to_pix'

Request you to please help

**Comment by AmitMY** [comment]
Thank you for your explanation.
It is now fixed, and the commands do run, for example:
```bash
pose_to_video --model=pix_to_pix --pose=sign.pose --video=sign.mp4 --upscale
```

Please understand however, that what you are running is under "Next steps" which is *NOT* ready.
For example, this pix_to_pix model yields very bad results, and I plan to rework it in the next month or so, as well as the stylegan model.

**Comment by hacker009-sudo** [comment]
Thanks for the explanation. Will wait for the final implementation.

**Comment by AmitMY** [comment]
I had some time yesterday to re-train and fix some issues https://github.com/sign-language-processing/transcription/commit/a308b5868f16290623f3f0f408b6a151905e0e82

The output is now more reasonable. I'll let it train for another day or two, and then deploy it

https://github.com/sign-language-processing/transcription/assets/5757359/ebf8c355-0e4e-4946-98ec-bf60e71e70a7

**Comment by AmitMY** [comment]
Pose to video moved to https://github.com/sign-language-processing/pose-to-video
